### ISSUE TITLE
R installation failed

### ISSUE THREAD

**Issue by zswgzx** [spisakt/pTFCE#5]
OS: ubuntu 16.04LTS
R: v3.6.1
Rstudio: 1.2.1335
issue:

install_github("spisakt/pTFCE")
Downloading GitHub repo spisakt/pTFCE@master
✔  checking for file ‘/tmp/RtmpqsNp2W/remotes19347326a571/spisakt-pTFCE-309a772/DESCRIPTION’ ...
─  preparing ‘pTFCE’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘pTFCE_0.2.0.0.tar.gz’
   
Installing package into ‘/home/shengwei/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘pTFCE’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error : 'use_package' is not an exported object from 'namespace:devtools'
Error: unable to load R code in package ‘pTFCE’
Execution halted
ERROR: lazy loading failed for package ‘pTFCE’
* removing ‘/home/shengwei/R/x86_64-pc-linux-gnu-library/3.6/pTFCE’
Error: Failed to install 'pTFCE' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpqsNp2W/file193471772f20/pTFCE_0.2.0.0.tar.gz’ had non-zero exit status

**Comment by spisakt** [comment]
Thank you for the report and sorry for the late replay.
I have just release version 0.2.1, which should already install well.

Tamas
